### ISSUE TITLE
Unable to create doris cluster for operator versions > 1.0.1

### ISSUE THREAD

**Issue by swapkh91** [linsoss/doris-operator#34]
@Al-assad tried to install doris operator 1.0.3 and create a new doris cluster
I'm seeing the below errors in `doris-operator-controller-manager` logs
```
pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:doris-operator-system:doris-operator-controller-manager" cannot list resource "deployments" in API group "apps" at the cluster scope

pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:doris-operator-system:doris-operator-controller-manager" cannot list resource "deployments" in API group "apps" at the cluster scope
```

and after some time
```
2023-12-05T08:50:40Z	ERROR	Could not wait for Cache to sync	{"controller": "dorismonitor", "controllerGroup": "al-assad.github.io", "controllerKind": "DorisMonitor", "error": "failed to wait for dorismonitor caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.DorisMonitor"}

2023-12-05 14:20:40.115 IST
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1
2023-12-05 14:20:40.115 IST
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:202
2023-12-05 14:20:40.115 IST
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
2023-12-05 14:20:40.115 IST
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:207
2023-12-05 14:20:40.115 IST
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
2023-12-05 14:20:40.115 IST
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:233
2023-12-05 14:20:40.115 IST
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
2023-12-05 14:20:40.115 IST
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219
2023-12-05 14:20:40.115 IST
2023-12-05T08:50:40Z	INFO	Stopping and waiting for non leader election runnables

2023-12-05 14:20:40.115 IST
2023-12-05T08:50:40Z	INFO	shutting down server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
2023-12-05 14:20:40.115 IST
2023-12-05T08:50:40Z	ERROR	error received after stop sequence was engaged	{"error": "failed to wait for dorisautoscaler caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.DorisAutoscaler"}
```

due to this, if I apply the doris-cluster yaml, no pod is created, same for version 1.0.2
version 1.0.1 doesn't show these errors

**Comment by Al-assad** [comment]
> @Al-assad tried to install doris operator 1.0.3 and create a new doris cluster I'm seeing the below errors in `doris-operator-controller-manager` logs
> 
> ```
> pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:doris-operator-system:doris-operator-controller-manager" cannot list resource "deployments" in API group "apps" at the cluster scope
> 
> pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:doris-operator-system:doris-operator-controller-manager" cannot list resource "deployments" in API group "apps" at the cluster scope
> ```
> 
> and after some time
> 
> ```
> 2023-12-05T08:50:40Z	ERROR	Could not wait for Cache to sync	{"controller": "dorismonitor", "controllerGroup": "al-assad.github.io", "controllerKind": "DorisMonitor", "error": "failed to wait for dorismonitor caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.DorisMonitor"}
> 
> 2023-12-05 14:20:40.115 IST
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1
> 2023-12-05 14:20:40.115 IST
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:202
> 2023-12-05 14:20:40.115 IST
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
> 2023-12-05 14:20:40.115 IST
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:207
> 2023-12-05 14:20:40.115 IST
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
> 2023-12-05 14:20:40.115 IST
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:233
> 2023-12-05 14:20:40.115 IST
> sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1
> 2023-12-05 14:20:40.115 IST
> 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/manager/runnable_group.go:219
> 2023-12-05 14:20:40.115 IST
> 2023-12-05T08:50:40Z	INFO	Stopping and waiting for non leader election runnables
> 
> 2023-12-05 14:20:40.115 IST
> 2023-12-05T08:50:40Z	INFO	shutting down server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
> 2023-12-05 14:20:40.115 IST
> 2023-12-05T08:50:40Z	ERROR	error received after stop sequence was engaged	{"error": "failed to wait for dorisautoscaler caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.DorisAutoscaler"}
> ```
> 
> due to this, if I apply the doris-cluster yaml, no pod is created, same for version 1.0.2 version 1.0.1 doesn't show these errors

Doris Operator v1.0.3 changed the DorisMonitor workload to statefulset, you just need to delete the DorisMonitor CRD that created before.

**Comment by swapkh91** [comment]
@Al-assad i tried upgrading from 1.0.1 to 1.0.2
getting the following error
```
pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:doris-operator-system:doris-operator-controller-manager" cannot list resource "deployments" in API group "apps" at the cluster scope

pkg/mod/k8s.io/client-go@v0.27.2/tools/cache/reflector.go:231: Failed to watch *v1.Deployment: failed to list *v1.Deployment: deployments.apps is forbidden: User "system:serviceaccount:doris-operator-system:doris-operator-controller-manager" cannot list resource "deployments" in API group "apps" at the cluster scope
```

Steps I followed to upgrade
1. setup doris cluster using operator 1.0.1
2. run `kubectl delete crd dorismonitors.al-assad.github.io` to delete DorisMonitor CRD
3. run `flux pull artifact oci://ghcr.io/linsoss/kustomize/doris-operator:1.0.2 --output ./doris-operator/` to pull 1.0.2 version
4. reapply operator yaml `kubectl apply -k doris-operator`

@Al-assad  what am I missing?
